{
 "title": "CPU usage per pod",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "p50 HTTP latency (Go app)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod restart count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (kube_pod_container_status_restarts_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Memory per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}